#include<bits/stdc++.h>
using namespace std;
int main(){
    int a;
    char b;
    if(a>=200){
        if(b == "b"){
            cout<<"1";
        }
        else{
            cout<<"2";
        }
    }
    else if(a>=100){
        if(b == "b"){
            cout<<"4";
        }
        else{
            cout<<"3";
        }
    }
    else if(a>=50){
        if(b == "b"){
            cout<<"5";
        }
        else{
            cout<<"6";
        }
    }


    return 0;
    
}