#include<iostream>
#include<windows.h>
using namespace std;
int main(){
    cout<<"     iiiiiiiiii\n";
    cout<<"   |           |\n";
    cout<<"   |:H:a:p:p:y:|\n";
    cout<<" __|___________|__\n";
    cout<<"|^^^^^^^^^^^^^^^^^|\n";
    cout<<"|                 |\n";
    cout<<"|:B:i:r:t:h:D:a:y:|\n";
    cout<<"|                 |\n";
    cout<<"~~~~~~~~~~~~~~~~~~~\n";
    Sleep(5000);
    return 0;
}