#include<iostream>
#include<windows.h>
using namespace std;
int main(){
	cout<<"1"<<endl;
	Sleep(1000); 
    system("cls");
    cout<<"2"<<endl;
    Sleep(1000);
    system("cls");
    cout<<"3"<<endl;
    Sleep(1000);
    system("cls");
    cout<<"4"<<endl;
    Sleep(1000);
    system("cls");
    cout<<"5"<<endl;
    Sleep(1000);
    system("cls");
    cout<<"6"<<endl;
    Sleep(1000);
    system("cls");
    cout<<"7"<<endl;
    Sleep(1000);
    system("cls");
    cout<<"8"<<endl;
    Sleep(1000);
    system("cls");
    cout<<"9"<<endl;
    Sleep(1000);
    system("cls");
    return 0;
}
